### PR TITLE
previewed version of different resolution (from 1920x1080px to 1440x1024px) and adding first typescript for managing htmls

### PR DESCRIPTION
**Pull request by Mariusz-Borczuk**
image

### CODE REVIEW

**Review by FilipParyz — DISMISSED** [review]
Great files 🤣

**Review by mmisiewiczz — APPROVED** [review]
ok

**Review by mmisiewiczz — APPROVED** [review]
nice

**Review by martamisiewicz — APPROVED** [review]
ok

**Review by FilipParyz — APPROVED** [review]

**Review by FilipParyz — APPROVED** [review]

**Review by FilipParyz — APPROVED** [review]

**Review by FilipParyz — APPROVED** [review]

**Pull request closed without merging**
